DIMENTION_OF_A_CELL = 25
NUM_OF_ROWS = 4
NUM_OF_COLUMNS = 5
WIDTH_GRID, HEIGHT_GRID = DIMENTION_OF_A_CELL * \
    NUM_OF_COLUMNS, DIMENTION_OF_A_CELL*NUM_OF_ROWS
NUMBER_OF_CELLS = NUM_OF_ROWS*NUM_OF_COLUMNS

MARGIN_LEFT = 0
if NUM_OF_COLUMNS <= 20:
    MARGIN_LEFT = (20-NUM_OF_COLUMNS)*DIMENTION_OF_A_CELL
    
MARGIN_TOP = 0
if NUM_OF_ROWS <= 20:
    MARGIN_TOP = (20-NUM_OF_ROWS)*DIMENTION_OF_A_CELL

DISPLAY_WIDTH = WIDTH_GRID+2*MARGIN_LEFT
DISPLAY_HEIGHT = HEIGHT_GRID+2*MARGIN_TOP
SIZE = DISPLAY_WIDTH, DISPLAY_HEIGHT
