DIMENTION_OF_A_CELL = 35
NUM_OF_ROWS = 4
NUM_OF_COLUMNS = 5
NUM_MIN_ROWS = 10
NUM_MIN_COLS = 10
WIDTH_GRID, HEIGHT_GRID = (
    DIMENTION_OF_A_CELL * NUM_OF_COLUMNS,
    DIMENTION_OF_A_CELL * NUM_OF_ROWS,
)
NUMBER_OF_CELLS = NUM_OF_ROWS * NUM_OF_COLUMNS

MARGIN_LEFT = 0
if NUM_OF_COLUMNS <= NUM_MIN_COLS:
    MARGIN_LEFT = (NUM_MIN_COLS - NUM_OF_COLUMNS) * DIMENTION_OF_A_CELL

MARGIN_TOP = 0
if NUM_OF_ROWS <= NUM_MIN_ROWS:
    MARGIN_TOP = (NUM_MIN_ROWS - NUM_OF_ROWS) * DIMENTION_OF_A_CELL

DISPLAY_WIDTH = WIDTH_GRID + 2 * MARGIN_LEFT
DISPLAY_HEIGHT = HEIGHT_GRID + 2 * MARGIN_TOP
SIZE = DISPLAY_WIDTH, DISPLAY_HEIGHT
